name: Dispatcher
on:
  push:
    branches: [main]

jobs:
  dispatch:
    name: Dispatch
    env:
      PACKAGES_TO_UPGRADE: ${{ needs.run_publish.outputs.packages }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["locoworks/home"]
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
          curl -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.PAT }}" \
          --request POST \
          --data '{"event_type": "deploy"}' https://api.github.com/repos/${{ matrix.repo }}/dispatches
